name: Deploy to github pages
on:
  push:                  # we push to develop, or...
    branches: [ develop ]
  workflow_dispatch:     # we select the action manually from the github console

jobs:
  gh-pages-deploy:
    name: Deploying to gh-pages
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v2
        with:
          node-version:  16.x
          
      - name: Checkout branch
        uses: actions/checkout@v2
      
      - name: Enable script
        run: chmod +x "./.github/deploy-gh-pages.sh"
        shell: bash

      - name: Run deploy script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: "./.github/deploy-gh-pages.sh"
        shell: bash